apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ifn-stats
  labels:
    app: mnp-ifn
spec:
  schedule: "30 7 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ifn-stats
              image: us.gcr.io/metacellllc/ifn/ifn-stats:{VERSION}
              imagePullPolicy: IfNotPresent
              env:
              - name: SLACK_WEBHOOK
                valueFrom:
                  secretKeyRef:
                    name: slackwebhook
                    key: webhook.txt
              resources:
                limits:
                  cpu: 100m
                  memory: 256Mi
                requests:
                  cpu: 10m
                  memory: 32Mi
